[repository]
name = "{{ cookiecutter.__project_slug }}"
changelog = "CHANGELOG.md"
version = "version.txt"
container_images_prefix = "{{ cookiecutter.__container_image_prefix }}"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "{{ cookiecutter.python_package_name }}"
path = "backend"
code_path = "src/{{ cookiecutter.__package_path }}"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "{{ cookiecutter.frontend_addon_name }}"
path = "frontend/packages/{{ cookiecutter.frontend_addon_name }}"
code_path = "src"
changelog = "frontend/packages/{{ cookiecutter.frontend_addon_name }}/CHANGELOG.md"
towncrier_settings = "frontend/packages/{{ cookiecutter.frontend_addon_name }}/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "{{ cookiecutter.__cookieplone_template }}"
template_version = "{{ cookiecutter.__generator_sha }}"
generated_date = "{{ cookiecutter.__generator_date_long }}"
